[program:highlight-manager]
directory=/opt/highlight-manager
command=/opt/highlight-manager/.venv/bin/python -m highlight_manager
autostart=true
autorestart=true
stderr_logfile=/var/log/highlight-manager.err.log
stdout_logfile=/var/log/highlight-manager.out.log
environment=PYTHONUNBUFFERED="1"
